- name: Add YugabyteDB Alert Rules
  when: alerts_enabled
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: monitoring.coreos.com/v1
      kind: PrometheusRule
      metadata:
        labels:
          prometheus: yugabyte
          role: alert-rules
        name: prometheus-yugabyte-rules
        namespace: "{{ yugabyte_namespace }}"
      spec: "{{ lookup('file', 'alert-rules.yaml') | from_yaml }}"
