- name: Add Alert Rules
  when: alerts_enabled
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: monitoring.coreos.com/v1
      kind: PrometheusRule
      metadata:
        labels:
          prometheus: vault
          role: alert-rules
        name: prometheus-vault-rules
        namespace: "{{ vault_namespace }}"
      spec: "{{ lookup('file', 'alert-rules.yaml') | from_yaml }}"
