- name: Create Jaeger PodMonitor for tracing
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: monitoring.coreos.com/v1
      kind: PodMonitor
      metadata:
        name: tracing
        namespace: istio-system
        labels: "{{ prometheus_monitor_labels | from_yaml }}"
      spec:
        podMetricsEndpoints:
        - interval: 5s
          targetPort: "14269"
        selector:
          matchLabels:
            app: jaeger
