- name: Restore Proxmox Snapshot
  hosts: proxmox
  gather_facts: false

  tasks:
    - name: Stop and Inventory VMs
      delegate_to: 127.0.0.1
      community.general.proxmox_kvm:
        api_host: "{{inventory_hostname}}"
        api_user: "{{pve_api_user}}"
        api_token_id: "{{pve_token_id}}"
        api_token_secret: "{{pve_token_secret}}"
        node: "{{item.node}}"
        name: "{{item.name}}"
        force: true
        timeout: 120
        state: stopped
      loop: "{{vms}}"
      register: instances

    - name: Restore VM from Snapshot
      delegate_to: 127.0.0.1
      community.general.proxmox_snap:
        api_host: "{{inventory_hostname}}"
        api_user: "{{pve_api_user}}"
        api_token_id: "{{pve_token_id}}"
        api_token_secret: "{{pve_token_secret}}"
        vmid: "{{item.vmid}}"
        state: rollback
        snapname: "{{ snapname | default('pre-install') }}"
      loop:  "{{ instances.results }}"

    - name: Restart VMs
      delegate_to: 127.0.0.1
      community.general.proxmox_kvm:
        api_host: "{{inventory_hostname}}"
        api_user: "{{pve_api_user}}"
        api_token_id: "{{pve_token_id}}"
        api_token_secret: "{{pve_token_secret}}"
        node: "{{item.node}}"
        name: "{{item.name}}"
        state: started
      loop: "{{vms}}"
